### ISSUE TITLE
Transfer ownership to RIT Wallace Memorial Library GitHub organization

### ISSUE THREAD

**Issue by peterdimou** [rit-wml/dublin-core-text-parser#35]
In order to ensure the preservation of this code, please transfer ownership of this repository to @rit-wml.

**Comment by atla5** [comment]
Would you add me to the organization? I wouldn't want either of us to have to go through the pull request process every time I try to commit to this repo or create/transfer other projects I'm working on. 

Thanks!

**Comment by atla5** [comment]
The transfer ownership request has been sent. 

The [documentation](https://help.github.com/articles/about-repository-transfers/) says "the new owner will receive an email giving the option to accept or reject the transfer." 

I assume it's going to your email address and not the main one for the library's? Either way, there's a 24-hour timeout set on the approval.

**Comment by atla5** [comment]
looks like you got it. haha. 

thanks very much!
