### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by atla5** [rit-wml/dublin-core-text-parser#36]
I haven't gone through the process of putting a license on this yet, and I'm not sure which I'd recommend. 

I know I've used the MIT License before, but the following may help:
- [ **comparative list** ](http://choosealicense.com/licenses/)
- [guide/documentation](http://copyleft.org/guide/)
- [simplified clickable decision tree](http://choosealicense.com/)

**Comment by peterdimou** [comment]
Some conversations have to happen before we decide which Open Source license (if any) get added to this project. For now, assume nothing has changed and continue contributing to the project without adding a license. Thanks!

**Comment by atla5** [comment]
It seems to me that the [MIT](http://choosealicense.com/licenses/mit/) and [Apache 2.0](http://choosealicense.com/licenses/apache-2.0/) licenses make the most sense.

_both_ permit
- commercial use
- distribution 
- modification
- private use

...without warranty (hold user/distributor liable) under the condition that the user includes a copy of the license.

_However_, the Apache 2.0 license allows for patent use (while holding onto the trademark). The MIT license does not.

Given this, and as the creator of the project, **I'd recommend MIT**.

**Comment by peterdimou** [comment]
Thank you for your recommendation. As I stated before, there are some conversations that need to happen internally before any further decision is made.
